### PR TITLE
add option to evaluate API key

### PR DESCRIPTION
**Pull request by raspbeguy**
Useful to specify one's own way to get the key, including pass with a different path.

### CODE REVIEW

**Comment by marcoradocchia** [comment]
The idea of letting the user choose it's own way to retrieve the api key sounds interesting, but the idea of letting `youterm` run arbitrary shell commands might sound scary.
Anyway the concept of letting the user choose it's own command to retrieve the key can still be achieved invoking `youterm` with the `-a` command line argument. Below an example:
```
youterm -a "$(pass show <api_key_entry>)"
```
or even without the need of using `pass`:
```
youterm -a "$(<shell_command>)"
```
What do you think about it?

By the way, thanks for contributing to the project, I really appreciate it!

**Comment by raspbeguy** [comment]
You're right, that's a good idea.

Nevertheless, thinking about that, and it's probably out of this MR scope, I think that might be useful to store the credentials (or the command to get it) in a config file instead of adding it to the command line. You could also create an alias in your shell but I think relying on shell config is not a good idea, that's why I think a config file is the right solution. The thing is, you can't use bash substitution in a config file.

My idea would be to check for the config file existence and if missing, just stick to current options.

So tell me what you think about it. If you think a config file is a good idea I'll work on it and will propose a new MR.

**Comment by marcoradocchia** [comment]
I've been avoiding using a config file for this purpose because I didn't like having the api key stored in plain text. However, it's ok to me to check for a config file and if missing then fallback to the current options, like you say, because this way the user may choose wheter or not to store the api key in the config file.
One thing is important though: currently `youterm` works on every platform and OS that can execute Python code and have `mpv`/`youtube-dl` installed. It has been successfully tested, for example, on Linux, Windows, and even Termux (Android). I'd like to keep it this way so the existence of the config file should be checked at a path that is OS dependent.
What do you think?

**Comment by raspbeguy** [comment]
Sorry for the lag, I had some other business to care about.

As I see it, the config file would make possible to set a cleartext password or a command to evaluate it. That means that youterm would have to execute some arbitrary code, but I don't think this is such a big deal. A lot of programs have such a feature.

Of course the config file would be facultative and as I proposed earlier, in case it's missing the program would stick to current behaviour, so I think that solves your concerns about compatibility with various platforms.

**Comment by marcoradocchia** [comment]
> Sorry for the lag, I had some other business to care about.
> 
> As I see it, the config file would make possible to set a cleartext password or a command to evaluate it. That means that youterm would have to execute some arbitrary code, but I don't think this is such a big deal. A lot of programs have such a feature.
> 
> Of course the config file would be facultative and as I proposed earlier, in case it's missing the program would stick to current behaviour, so I think that solves your concerns about compatibility with various platforms.

Okay, I think it makes sense. Let's work on config file for this and maybe even future purposes! What config format were you thinking about?

**Comment by raspbeguy** [comment]
My favorite format is yaml, but I am ok with anything I guess.

```yaml
# Clear text API key
api_key: "this is a secret key"

# Alternatively, a command to evaluate it
api_key_eval: "/usr/bin/pass path/to/my/api-key"
```

Both options are obviously mutually exclusive, so if they are both present I don't know whether it's better to silently use one over the other (and in this case, which one to prefer?) or just raise an exception.

**Comment by marcoradocchia** [comment]
> My favorite format is yaml, but I am ok with anything I guess.
> 
> ```yaml
> # Clear text API key
> api_key: "this is a secret key"
> 
> # Alternatively, a command to evaluate it
> api_key_eval: "/usr/bin/pass path/to/my/api-key"
> ```
> 
> Both options are obviously mutually exclusive, so if they are both present I don't know whether it's better to silently use one over the other (and in this case, which one to prefer?) or just raise an exception.

In the last commits I implemented the option to have a config file. A way to pass directly the API key or to set a custom `pass` entry name is already available, check source code. However `api_key_eval` is not yet present. If you want to implement it in the config parser feel free to integrate it and make a pull request.

**Pull request closed without merging**
